export const DO_SMTH = 'DO_SMTH';
export const SET_PREV_STATE = 'SET_PREV_STATE';
export const SET_IS_AUTHORIZED = 'SET_IS_AUTHORIZED';
export const SWITCH_GAME_SOUND = 'SWITCH_GAME_SOUND';
export const SET_AUDIOCHALLENGE_SETTINGS = 'SET_AUDIOCHALLENGE_SETTINGS';
export const SET_VOCABLUARY_SETTINGS = 'SET_VOCABLUARY_SETTINGS';
export const SET_WORDCONSTRUCTOR_SETTINGS = 'SET_WORDCONSTRUCTOR_SETTINGS';
